apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: datecronjob
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: datecronjob
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date 
            image: busybox
            name: datecronjob
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
