apiVersion: v1
kind: Pod
metadata:
  name: ram1
  namespace: default
  labels:
    name: ram
spec:
  containers:
  - name: ram1
    image: polinux/stress
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
