apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: setrollimage
  name: setrollimage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: setrollimage
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: setrollimage
    spec:
      containers:
      - image: nginx:1.21.0-alpine
        name: nginx
        resources: {}
status: {}
