apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: assignpod
  name: assignpod
spec:
  nodeSelector:
    disk: spinning
  containers:
  - image: nginx
    name: assignpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
