apiVersion: v1
kind: Pod
metadata:
  name: cpu-1
  namespace: default
  labels:
    name: cpu
spec:
  containers:
  - name: cpu-1
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"
