apiVersion: v1
kind: Pod
metadata:
  name: cpu-2
  namespace: default
  labels:
    name: cpu
spec:
  containers:
  - name: cpu-2
    image: vish/stress
    resources:
      limits:
        cpu: "0.5"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "1"
