apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: labelpod
  name: labelpod
spec:
  nodeSelector:
    disk: spinning
  containers:
  - image: nginx
    name: labelpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
