apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multiplecontainers
  name: multiplecontainers
spec:
  containers:
  - image: nginx
    name: multiplecontainers
  - image: redis
    name: redis
  - image: memcached
    name: memcached
  - image: consul
    name: consul
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
