apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: manifestpod
  name: manifestpod
spec:
  containers:
  - image: nginx
    name: manifestpod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
