apiVersion: v1
kind: Pod
metadata:
  labels:
    run: schedulepod
  name: schedulepod
spec:
  containers:
  - args:
    - /bin/sleep
    - "3600"
    image: busybox
    name: schedulepod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "a100"
    effect: "NoSchedule"
