apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: schedulepod1
  name: schedulepod1
spec:
  containers:
  - args:
    - /bin/sleep
    - "3600"
    image: busybox
    name: schedulepod1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "key1"
    operator: "Exists"
    #    value: "value"
    effect: "NoSchedule"
status: {}
