apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  storageClassName: csi-hostpath
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/app-cfg"
