apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secretpod
  name: secretpod
spec:
  containers:
  - args:
    - /bin/sleep
    - "3600"
    image: busybox
    name: secretpod
    resources: {}
    volumeMounts:
    - name: acpw
      mountPath: "/etc/info"
      readOnly: true
  volumes:
  - name: acpw
    secret:
      secretName: mypasswd
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
